### PR TITLE
ref(*): replace centos with alpine

### PR DESCRIPTION
**Pull request by aledbf**
```
deis/example-dockerfile-python      alpine        aedc8917efff        4 seconds ago       41.2 MB
deis/example-dockerfile-python      latest        833b50d414e1        8 days ago           210 MB
```

### CODE REVIEW

**Comment by aledbf** [comment]
ping @mboersma

**Comment by mboersma** [comment]
Awesome, code LGTM.

**Comment by mboersma** [comment]
@aledbf this needs to be rebased since we removed the `MAINTAINER` line. :steam_locomotive:

**Comment by mboersma** [comment]
LGTM.

``` console
$ git push deis master
Warning: Permanently added the RSA host key for IP address '[172.17.8.101]:2222' to the list of known hosts.
Counting objects: 46, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (44/44), done.
Writing objects: 100% (46/46), 6.86 KiB | 0 bytes/s, done.
Total 46 (delta 8), reused 0 (delta 0)

-----> Building Docker image
remote: build context to Docker daemon 5.632 kB
remote: build context to Docker daemon 
Step 0 : FROM gliderlabs/alpine:3.1
Pulling repository gliderlabs/alpine
a5b60fe97da5: Pulling image (3.1) from gliderlabs/alpine
a5b60fe97da5: Pulling image (3.1) from gliderlabs/alpine, endpoint: https://registry-1.docker.io/v1/
a5b60fe97da5: Pulling dependent layers
511136ea3c5a: Pulling metadata
511136ea3c5a: Pulling fs layer
511136ea3c5a: Download complete
a5b60fe97da5: Pulling metadata
a5b60fe97da5: Pulling fs layer
a5b60fe97da5: Download complete
a5b60fe97da5: Download complete
Status: Downloaded newer image for gliderlabs/alpine:3.1
 ---> a5b60fe97da5
Step 1 : RUN apk-install python
 ---> Running in 96554998a037
fetch http://dl-4.alpinelinux.org/alpine/v3.1/main/x86_64/APKINDEX.tar.gz
(1/9) Installing libbz2 (1.0.6-r3)
(2/9) Installing expat (2.1.0-r1)
(3/9) Installing libffi (3.0.13-r0)
(4/9) Installing gdbm (1.11-r0)
(5/9) Installing ncurses-terminfo-base (5.9-r3)
(6/9) Installing ncurses-libs (5.9-r3)
(7/9) Installing readline (6.3-r3)
(8/9) Installing sqlite-libs (3.8.7.4-r0)
(9/9) Installing python (2.7.9-r0)
Executing busybox-1.22.1-r14.trigger
OK: 45 MiB in 24 packages
 ---> 9d379d93d86f
Removing intermediate container 96554998a037
Step 2 : ADD . /app
 ---> f7a663716b96
Removing intermediate container 6ed099f2cded
Step 3 : WORKDIR /app
 ---> Running in 1da353b77e3d
 ---> 8ac0409b333d
Removing intermediate container 1da353b77e3d
Step 4 : CMD python -m SimpleHTTPServer 5000
 ---> Running in a7734316f015
 ---> e51fe25b20ec
Removing intermediate container a7734316f015
Step 5 : EXPOSE 5000
 ---> Running in 1b5f379bb365
 ---> 6f2611457bca
Removing intermediate container 1b5f379bb365
Step 6 : ENV GIT_SHA 0292b73127f845bfa2d5c140a473c5e3aab530b9
 ---> Running in 20aef23f0aad
 ---> bbdf671f8020
Removing intermediate container 20aef23f0aad
Successfully built bbdf671f8020
-----> Pushing image to private registry

-----> Launching... 
       done, yeoman-inventor:v2 deployed to Deis

       http://yeoman-inventor.local3.deisapp.com

       To learn more, use `deis help` or visit http://deis.io

To ssh://git@deis.local3.deisapp.com:2222/yeoman-inventor.git
 * [new branch]      master -> master
$ curl http://yeoman-inventor.local3.deisapp.com
<h1>Powered by Deis</h1>
```

**Comment by carmstrong** [comment]
:ship:

**Pull request merged**
